# Site settings
title: 芝苸
url: "http://xiaobaolovexiaomei.com"    # the protocol and hostname of your site, eg. `http://clark-zhao.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-BoHu` or just one slash `/`
#timezone: Asia/Shanghai
description: Jason的个人博客网站，编程、读书、杂文
# Your information
email: shaojhweb@gmail.com
author: js
place: 中国
domain: 互联网
company: null
position: null
school: 三本
major: 渔业
# resume: "http://zhaoyuxiang.cn/cv"
profile: Jason的个人博客网站，编程、读书、杂文
twitter_username: ms_jason
weibo_username:  ms_jason
github_username:  ms_jason

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: disqus_rBsrcAHSI0
# get one: https://disqus.com/admin/signup/
# duoshuo_shortname: clark-zhao
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 3
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
