# Site settings
title: Jason Bourne
email: "&#104;&#105;&#064;&#112;&#101;&#105;&#119;&#101;&#110;&#046;&#108;&#117;"
description: "Significant"
baseurl: ""
url: "http://xiaobaolovexiaomei.com"
permalink: /:year/:title


# Social account
# twitter:  PeiwenLu
# weibo:    ID
github:   webbings
# codepen:  P233
# dribbble: username


# Comment
# disqus_shortname:


# Google Analytics
# google_analytics: UA-60830414-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
